version: '3.3'
services:
  mysql_db:
    container_name: mysql_test
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'edwin'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '32769:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  
# Names our volume
volumes:
  mysql-volume:
